CREATE SCHEMA IF NOT EXISTS app;
CREATE TABLE IF NOT EXISTS app.user(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'USER'
);

CREATE TABLE IF NOT EXISTS app.user_credentials(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_name TEXT NOT NULL REFERENCES app.user(email),
    password TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE'
);
